% Pairwise correlations between all the major statistics, including d'

% A supplemental figure of the pairwise correlations at f_mod = 150Hz for
% the four successful statistics. 
stats_oneperunit_stacked.SACpeaks1234sum_150ish_p0001 = ...
    stats_oneperunit_stacked.SACpeak0sal_150ish_p0001 + ...
    stats_oneperunit_stacked.SACpeak2sal_150ish_p0001 + ...
    stats_oneperunit_stacked.SACpeak3sal_150ish_p0001 + ...
    stats_oneperunit_stacked.SACpeak4sal_150ish_p0001;

stackinds = find(stats_oneperunit_stacked.allamfreqs==150 | ...
                stats_oneperunit_stacked.allamfreqs==200);

plotPairWise({'Classifier metric (c'')','Z_I_S_I','Sum of SAC Peaks','Neural fluctuation','Neural reliability'}, ...                         
                          stats_oneperunit_stacked.dprimes(stackinds), ...
                          stats_oneperunit_stacked.Z(stackinds), ...
                          stats_oneperunit_stacked.SACpeaks1234sum_150ish_p0001(stackinds), ...
                          stats_oneperunit_stacked.envFluct_R150ish_0p48ms(stackinds), ...
                          stats_oneperunit_stacked.reliability_R150ish_0p24ms(stackinds) ...
                          )
% print -dtiff -r300 FigureS8_statistic_correlations.tiff;

